import { BookOpenCheck, Check, Clock3, Flag, RefreshCw, Save, Target } from "lucide-react";
import { FormEvent, useEffect, useState } from "react";
import { getDashboard, setGradeGoal, type DashboardData, type DashboardSubject } from "../api";
import { getWeeklyStudyGoal, saveWeeklyStudyGoal } from "../utils/studyGoal";

type GoalSubject = { subject: DashboardSubject; detail: DashboardData };
const clamp = (value: number) => Math.max(0, Math.min(100, value));

export default function GoalsPage() {
  const [dashboard, setDashboard] = useState<DashboardData | null>(null); const [subjects, setSubjects] = useState<GoalSubject[]>([]); const [weeklyGoal, setWeeklyGoal] = useState<number | null>(getWeeklyStudyGoal); const [weeklyInput, setWeeklyInput] = useState(String(getWeeklyStudyGoal() ?? 120)); const [editingGrade, setEditingGrade] = useState<number | null>(null); const [gradeInput, setGradeInput] = useState(""); const [saving, setSaving] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null);
  async function load() { setLoading(true); setError(null); try { const global = await getDashboard(); const details = await Promise.all(global.subjects.map(async (subject) => ({ subject, detail: await getDashboard(subject.id) }))); setDashboard(global); setSubjects(details); } catch (caught) { setError(caught instanceof Error ? caught.message : "No se pudieron cargar los objetivos."); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, []);
  function submitWeekly(event: FormEvent) { event.preventDefault(); const value = Number(weeklyInput); if (!Number.isFinite(value) || value < 30 || value > 10000) { setError("El objetivo semanal debe estar entre 30 y 10.000 minutos."); return; } saveWeeklyStudyGoal(value); setWeeklyGoal(value); setError(null); setNotice("Objetivo semanal guardado."); window.setTimeout(() => setNotice(null), 2500); }
  async function submitGrade(subjectId: number) { const value = Number(gradeInput); if (!Number.isFinite(value) || value < 0 || value > 10) { setError("La nota objetivo debe estar entre 0 y 10."); return; } setSaving(true); setError(null); try { await setGradeGoal(subjectId, value); setEditingGrade(null); setNotice("Objetivo de nota actualizado."); await load(); window.setTimeout(() => setNotice(null), 2500); } catch (caught) { setError(caught instanceof Error ? caught.message : "No se pudo guardar el objetivo."); } finally { setSaving(false); } }
  if (loading) return <section className="uc-page-shell uc-state-page"><p className="uc-eyebrow">Objetivos</p><h1>Preparando tu progreso…</h1><p>Reuniendo metas, notas y preparación por asignatura.</p></section>;
  if (error && !dashboard) return <section className="uc-page-shell uc-state-page"><p className="uc-eyebrow">Objetivos</p><h1>No se pudieron cargar tus objetivos.</h1><p>{error}</p><button className="uc-primary-action" onClick={() => void load()}>Reintentar <RefreshCw size={16} /></button></section>;
  const studied = dashboard?.metrics.study_minutes_last_7_days ?? 0; const weeklyPercent = weeklyGoal ? clamp(studied / weeklyGoal * 100) : 0; const remaining = weeklyGoal ? Math.max(0, weeklyGoal - studied) : null;
  return <div className="uc-page-shell uc-goals-page"><header className="uc-page-intro"><div><p className="uc-eyebrow">Dirección académica</p><h1>¿Qué quieres conseguir?</h1><p className="uc-page-subtitle">Define el rumbo y compara tu progreso real en tiempo, nota y preparación.</p></div><div className="uc-date-chip"><Flag size={16} /> {subjects.length} asignatura{subjects.length === 1 ? "" : "s"}</div></header>{notice && <div className="uc-inline-success">{notice}</div>}{error && <div className="uc-inline-error">{error}</div>}
    <section className="uc-goal-time"><div className="uc-goal-time-copy"><p className="uc-eyebrow">Objetivo de tiempo</p><h2>{weeklyGoal ? `${weeklyGoal} min por semana` : "Define tu ritmo semanal"}</h2><p>{weeklyGoal ? remaining === 0 ? "Objetivo alcanzado esta semana." : `Faltan ${remaining} minutos para completar el objetivo.` : "El objetivo se guarda en este navegador y puede modificarse cuando cambie tu carga."}</p><form onSubmit={submitWeekly}><input type="number" min="30" max="10000" value={weeklyInput} onChange={(event) => setWeeklyInput(event.target.value)} aria-label="Minutos por semana" /><span>min / semana</span><button><Save size={14} /> Guardar</button></form></div><div className="uc-goal-time-progress"><strong>{weeklyGoal ? `${weeklyPercent.toFixed(0)}%` : "—"}</strong><span>{studied} min estudiados en los últimos 7 días</span><div className="uc-progress-track"><div className="uc-progress-fill blue" style={{ width: `${weeklyPercent}%` }} /></div><div className="uc-goal-time-subjects">{[...subjects].sort((a, b) => b.detail.metrics.study_minutes_last_7_days - a.detail.metrics.study_minutes_last_7_days).map(({ subject, detail }) => <div key={subject.id}><span>{subject.name}</span><strong>{detail.metrics.study_minutes_last_7_days} min</strong></div>)}</div></div></section>
    <section className="uc-goals-ledger"><header><div><p className="uc-eyebrow">Objetivo de nota</p><h2>Rendimiento por asignatura</h2></div><Target size={18} /></header><div className="uc-goal-columns"><span>Asignatura</span><span>Nota actual</span><span>Objetivo</span><span>Diferencia</span><span>Media restante</span></div>{subjects.map(({ subject }) => { const current = subject.grade.current_grade_out_of_10; const target = subject.grade.target_grade; const gap = current != null && target != null ? Math.max(0, target - current) : null; return <article key={subject.id}><strong>{subject.name}</strong><span>{current?.toFixed(1) ?? "—"}</span><span>{editingGrade === subject.id ? <span className="uc-inline-grade-edit"><input type="number" min="0" max="10" step="0.1" value={gradeInput} onChange={(event) => setGradeInput(event.target.value)} /><button disabled={saving} onClick={() => void submitGrade(subject.id)}><Check size={13} /></button></span> : <button className="uc-grade-goal-button" onClick={() => { setEditingGrade(subject.id); setGradeInput(String(target ?? "")); }}>{target?.toFixed(1) ?? "Definir"}</button>}</span><span>{gap != null ? `${gap.toFixed(1)} puntos` : "—"}</span><span>{subject.grade.required_average_on_remaining?.toFixed(1) ?? "—"}</span></article>; })}</section>
    <section className="uc-readiness-goals"><header><div><p className="uc-eyebrow">Objetivo de preparación</p><h2>Preparación para próximas evaluaciones</h2></div><BookOpenCheck size={18} /></header>{subjects.map(({ subject, detail }) => { const boss = detail.next_boss; const gap = boss ? Math.max(0, boss.target_score_percentage - boss.readiness_percentage) : null; return <article key={subject.id}><div><strong>{subject.name}</strong><span>{boss?.assessment_title ?? "Sin evaluación activa"}</span></div><div className="uc-readiness-goal-value"><strong>{boss ? `${boss.readiness_percentage.toFixed(1)}%` : "—"}</strong><span>{boss ? `/ ${boss.target_score_percentage.toFixed(0)}%` : "sin objetivo"}</span></div><div className="uc-progress-track"><div className="uc-progress-fill" style={{ width: `${boss?.readiness_percentage ?? 0}%` }} /></div><small>{gap != null ? gap === 0 ? "Objetivo alcanzado" : `Faltan ${gap.toFixed(1)} puntos` : "Sin preparación disponible"}</small></article>; })}</section>
    <p className="uc-goals-note"><Clock3 size={13} /> El objetivo de tiempo es una preferencia local. Los objetivos de nota y preparación utilizan tus datos académicos registrados.</p>
  </div>;
}
