import { Check, RefreshCw, Save, Target, X } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { getCurriculum, getDashboard, setGradeGoal, type CurriculumData, type DashboardData, type DashboardSubject } from "../api";
import { getGoalPreferences, saveGoalPreferences, type GoalPreferences } from "../utils/goalPreferences";

type GoalSubject = { subject: DashboardSubject; detail: DashboardData; curriculum: CurriculumData | null };
const clamp = (value: number) => Math.max(0, Math.min(100, value));

export default function GoalsPage() {
  const [dashboard, setDashboard] = useState<DashboardData | null>(null); const [subjects, setSubjects] = useState<GoalSubject[]>([]); const [preferences, setPreferences] = useState<GoalPreferences>(getGoalPreferences); const [draft, setDraft] = useState<GoalPreferences>(getGoalPreferences);
  const [panelOpen, setPanelOpen] = useState(false); const [editingSubject, setEditingSubject] = useState<number | null>(null); const [gradeInput, setGradeInput] = useState(""); const [saving, setSaving] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null);

  async function load(background = false) {
    if (!background) setLoading(true); setError(null);
    try {
      const global = await getDashboard();
      const details = await Promise.all(global.subjects.map(async (subject) => { const [detail, curriculum] = await Promise.all([getDashboard(subject.id), getCurriculum(subject.id).catch(() => null)]); return { subject, detail, curriculum }; }));
      setDashboard(global); setSubjects(details);
    } catch (caught) { setError(caught instanceof Error ? caught.message : "No se pudieron cargar los objetivos."); } finally { setLoading(false); }
  }
  useEffect(() => { void load(); }, []);

  function saveGeneral() {
    if (draft.weeklyMinutes < 30 || draft.dailyMinutes < 10 || draft.studyDays < 1 || draft.studyDays > 7 || draft.readinessTarget < 1 || draft.readinessTarget > 100) { setError("Revisa los objetivos: días 1–7, preparación 1–100 y tiempos positivos."); return; }
    saveGoalPreferences(draft); setPreferences(draft); setNotice("Objetivos de constancia y preparación guardados."); setError(null);
  }
  async function saveSubject(subjectId: number) {
    const target = Number(gradeInput); if (!Number.isFinite(target) || target < 0 || target > 10) { setError("La nota objetivo debe estar entre 0 y 10."); return; }
    setSaving(true); setError(null);
    try { await setGradeGoal(subjectId, target); saveGoalPreferences(draft); setPreferences(draft); await load(true); setEditingSubject(null); setNotice("Cambios guardados correctamente."); }
    catch (caught) { setError(caught instanceof Error ? caught.message : "No se pudo guardar el objetivo."); } finally { setSaving(false); }
  }

  const averages = useMemo(() => { const current = subjects.flatMap(({ subject }) => subject.grade.current_grade_out_of_10 == null ? [] : [subject.grade.current_grade_out_of_10]); const target = subjects.flatMap(({ subject }) => subject.grade.target_grade == null ? [] : [subject.grade.target_grade]); return { current: current.length ? current.reduce((a, b) => a + b, 0) / current.length : null, target: target.length ? target.reduce((a, b) => a + b, 0) / target.length : null }; }, [subjects]);
  const readiness = useMemo(() => { const values = subjects.flatMap(({ detail }) => detail.next_boss?.readiness_percentage == null ? [] : [detail.next_boss.readiness_percentage]); return values.length ? values.reduce((a, b) => a + b, 0) / values.length : null; }, [subjects]);
  const mastery = useMemo(() => subjects.reduce((total, { curriculum }) => { const topics = curriculum?.units.flatMap((unit) => unit.topics.flatMap((topic) => [topic, ...topic.subtopics])) ?? []; return { mastered: total.mastered + topics.filter((item) => item.status === "mastered").length, total: total.total + topics.length }; }, { mastered: 0, total: 0 }), [subjects]);
  const studied = dashboard?.metrics.study_minutes_last_7_days ?? 0; const activeDays = dashboard?.analytics?.current.active_days ?? 0; const gap = averages.current != null && averages.target != null ? averages.target - averages.current : null;

  if (loading) return <section className="uc-page-shell uc-state-page"><p className="uc-eyebrow">Objetivos</p><h1>Preparando tu progreso…</h1></section>;
  if (error && !dashboard) return <section className="uc-page-shell uc-state-page"><p className="uc-eyebrow">Objetivos</p><h1>No se pudieron cargar tus objetivos.</h1><p>{error}</p><button className="uc-primary-action" onClick={() => void load()}>Reintentar <RefreshCw size={16} /></button></section>;

  return <div className="uc-page-shell uc-goals-page-v2">
    <header className="uc-page-intro"><div><p className="uc-eyebrow">Este semestre</p><h1>Objetivos con contexto.</h1><p className="uc-page-subtitle">Nota, tiempo y preparación en una sola dirección académica.</p></div><button className="uc-primary-action" onClick={() => setPanelOpen(true)}><Target size={15} /> Ver / editar por asignatura</button></header>
    {notice && <div className="uc-inline-success">{notice}</div>}{error && <div className="uc-inline-error">{error}</div>}
    <section className="uc-goal-performance"><header><p className="uc-eyebrow">Nota media objetivo</p><button className="uc-text-action" onClick={() => setPanelOpen(true)}>Editar</button></header><div className="uc-goal-grade-strip"><div><span>Actual</span><strong>{averages.current?.toFixed(1) ?? "—"}</strong></div><div><span>Objetivo</span><strong>{averages.target?.toFixed(1) ?? "—"}</strong></div><div><span>Diferencia</span><strong className={gap != null && gap > 0 ? "is-gap" : ""}>{gap == null ? "—" : `${gap >= 0 ? "+" : ""}${gap.toFixed(1)}`}</strong></div></div><div className="uc-grade-axis"><span className="is-current" style={{ left: `${clamp((averages.current ?? 0) * 10)}%` }} /><span className="is-target" style={{ left: `${clamp((averages.target ?? 0) * 10)}%` }} /></div><p>Calculada únicamente con notas y objetivos reales por asignatura.</p></section>
    <div className="uc-goal-secondary"><section className="uc-goal-consistency"><div><p className="uc-eyebrow">Tiempo y constancia</p><h2>{studied} <small>min esta semana</small></h2><p>{activeDays} de {preferences.studyDays} días objetivo con actividad.</p></div><div className="uc-progress-track"><div className="uc-progress-fill blue" style={{ width: `${clamp(studied / preferences.weeklyMinutes * 100)}%` }} /></div><div className="uc-goal-fields"><label>Min / semana<input type="number" min="30" value={draft.weeklyMinutes} onChange={(event) => setDraft({ ...draft, weeklyMinutes: Number(event.target.value) })} /></label><label>Min / día<input type="number" min="10" value={draft.dailyMinutes} onChange={(event) => setDraft({ ...draft, dailyMinutes: Number(event.target.value) })} /></label><label>Días / semana<input type="number" min="1" max="7" value={draft.studyDays} onChange={(event) => setDraft({ ...draft, studyDays: Number(event.target.value) })} /></label></div></section><section className="uc-goal-readiness"><div><p className="uc-eyebrow">Preparación</p><h2>{readiness != null ? `${readiness.toFixed(0)}%` : "Sin estimación"}</h2><p>{mastery.mastered} de {mastery.total} temas dominados según el temario persistido.</p></div><div className="uc-readiness-line"><span style={{ width: `${readiness ?? 0}%` }} /></div><label className="uc-goal-readiness-input">Objetivo de preparación<input type="number" min="1" max="100" value={draft.readinessTarget} onChange={(event) => setDraft({ ...draft, readinessTarget: Number(event.target.value) })} /><span>%</span></label></section></div>
    <button className="uc-goal-save-general" onClick={saveGeneral}><Save size={14} /> Guardar objetivos generales</button>
    {panelOpen && <div className="uc-goal-drawer-layer"><button className="uc-overlay" aria-label="Cerrar" onClick={() => setPanelOpen(false)} /><aside className="uc-goal-drawer uc-goal-drawer-v2"><header><div><p className="uc-eyebrow">Objetivos por asignatura</p><h2>Rendimiento y dedicación</h2></div><button onClick={() => setPanelOpen(false)} aria-label="Cerrar"><X size={18} /></button></header><div className="uc-goal-subject-list">{subjects.map(({ subject, detail }) => { const local = draft.subjects[String(subject.id)] ?? { weeklyMinutes: draft.weeklyMinutes, readinessTarget: draft.readinessTarget }; const editing = editingSubject === subject.id; return <article key={subject.id}><header><div><strong>{subject.name}</strong><small>{subject.grade.evaluated_weight_percentage.toFixed(0)}% evaluado</small></div>{!editing && <button className="uc-text-action" onClick={() => { setEditingSubject(subject.id); setGradeInput(String(subject.grade.target_grade ?? "")); }}>Editar</button>}</header><div className="uc-subject-goal-values"><span>Actual <strong>{subject.grade.current_grade_out_of_10?.toFixed(1) ?? "—"}</strong></span><span>Objetivo <strong>{subject.grade.target_grade?.toFixed(1) ?? "—"}</strong></span><span>Preparación <strong>{detail.next_boss?.readiness_percentage?.toFixed(0) ?? "—"}%</strong></span></div>{editing && <div className="uc-subject-goal-editor"><label>Nota objetivo<input type="number" min="0" max="10" step="0.1" value={gradeInput} onChange={(event) => setGradeInput(event.target.value)} /></label><label>Min / semana<input type="number" min="30" value={local.weeklyMinutes} onChange={(event) => setDraft({ ...draft, subjects: { ...draft.subjects, [subject.id]: { ...local, weeklyMinutes: Number(event.target.value) } } })} /></label><label>Preparación<input type="number" min="1" max="100" value={local.readinessTarget} onChange={(event) => setDraft({ ...draft, subjects: { ...draft.subjects, [subject.id]: { ...local, readinessTarget: Number(event.target.value) } } })} /></label><button className="uc-primary-action" disabled={saving} onClick={() => void saveSubject(subject.id)}>{saving ? "Guardando…" : "Guardar cambios"} <Check size={13} /></button></div>}<footer><span>Necesitas en lo restante</span><strong>{subject.grade.required_average_on_remaining?.toFixed(1) ?? "—"}</strong></footer></article>; })}</div></aside></div>}
  </div>;
}
