import { AlertCircle, ArrowLeft, CheckCircle2, Clock3, FileText, RefreshCw } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { getJob, getJobs, type JobDetail, type JobSummary } from "../api";

const statusCopy = { pending: "En proceso", running: "En proceso", completed: "Completado", failed: "No completado" };
function formatDate(value: string | null) { return value ? new Date(value).toLocaleString("es-ES", { day: "2-digit", month: "short", hour: "2-digit", minute: "2-digit" }) : "—"; }

export default function JobsPage() {
  const [jobs, setJobs] = useState<JobSummary[]>([]); const [selected, setSelected] = useState<JobDetail | null>(null);
  const [loading, setLoading] = useState(true); const [detailLoading, setDetailLoading] = useState(false); const [error, setError] = useState<string | null>(null); const [filter, setFilter] = useState("all");

  async function load(silent = false) { if (!silent) setLoading(true); setError(null); try { const response = await getJobs(); setJobs(response.jobs); if (selected) { const refreshed = await getJob(selected.id); setSelected(refreshed.job); } } catch (caught) { setError(caught instanceof Error ? caught.message : "No se pudieron cargar los trabajos."); } finally { setLoading(false); } }
  async function open(job: JobSummary) { setDetailLoading(true); setError(null); try { setSelected((await getJob(job.id)).job); } catch (caught) { setError(caught instanceof Error ? caught.message : "No se pudo abrir el trabajo."); } finally { setDetailLoading(false); } }
  useEffect(() => { void load(); const timer = window.setInterval(() => void load(true), 15000); return () => window.clearInterval(timer); }, [selected?.id]);
  const visible = useMemo(() => jobs.filter((job) => filter === "all" || (filter === "processing" ? job.status === "pending" || job.status === "running" : job.status === filter)), [jobs, filter]);
  const counts = { processing: jobs.filter((job) => job.status === "pending" || job.status === "running").length, completed: jobs.filter((job) => job.status === "completed").length };

  if (loading) return <section className="uc-page-shell uc-state-page"><p className="uc-eyebrow">Jobs</p><h1>Consultando trabajos en segundo plano…</h1><p>Recuperando estado y resultados persistidos.</p></section>;
  if (error && !jobs.length) return <section className="uc-page-shell uc-state-page"><p className="uc-eyebrow">Jobs</p><h1>No se pudo conectar con UniCore.</h1><p>{error}</p><button className="uc-primary-action" onClick={() => void load()}>Reintentar <RefreshCw size={16} /></button></section>;
  if (selected) return <div className="uc-page-shell uc-job-detail"><button className="uc-back-link" onClick={() => setSelected(null)}><ArrowLeft size={16} /> Todos los trabajos</button><header className="uc-page-intro"><div><p className="uc-eyebrow">Resultado de trabajo</p><h1>{selected.objective}</h1><p className="uc-page-subtitle">{selected.kind} · creado {formatDate(selected.created_at)}</p></div><span className={`uc-job-status is-${selected.status}`}>{statusCopy[selected.status]}</span></header>{detailLoading ? <div className="uc-empty-inline">Actualizando resultado…</div> : <section className="uc-job-result"><aside><p className="uc-eyebrow">Estado</p><dl><div><dt>Inicio</dt><dd>{formatDate(selected.started_at)}</dd></div><div><dt>Finalización</dt><dd>{formatDate(selected.completed_at)}</dd></div><div><dt>Salida esperada</dt><dd>{selected.expected_output}</dd></div></dl><button className="uc-text-action" onClick={() => void open(selected)}><RefreshCw size={14} /> Actualizar estado</button></aside><article><p className="uc-eyebrow">{selected.status === "failed" ? "No completado" : "Resultado"}</p>{selected.status === "completed" && selected.result ? <div className="uc-job-result-text">{selected.result}</div> : selected.status === "failed" ? <div className="uc-job-error"><AlertCircle size={17} />{selected.error ?? "Este trabajo no pudo completarse."}</div> : <div className="uc-job-processing"><Clock3 size={18} /><strong>El análisis sigue en proceso.</strong><span>Esta vista se actualiza automáticamente cada 15 segundos.</span></div>}</article></section>}</div>;

  return <div className="uc-page-shell uc-jobs-page"><header className="uc-page-intro"><div><p className="uc-eyebrow">Procesamiento académico</p><h1>Trabajos largos, sin ruido.</h1><p className="uc-page-subtitle">Sigue análisis delegados por el Agent y consulta sus resultados cuando estén listos.</p></div><button className="uc-date-chip uc-button-chip" onClick={() => void load()}><RefreshCw size={15} />Actualizar</button></header><section className="uc-job-summary uc-job-summary-compact"><div><span>En proceso</span><strong>{counts.processing}</strong><small>pendientes o ejecutándose</small></div><div><span>Completados</span><strong>{counts.completed}</strong><small>resultado disponible</small></div></section><section className="uc-job-register"><div className="uc-job-register-head"><div><p className="uc-eyebrow">Registro</p><h2>Actividad reciente</h2></div><div className="uc-task-filters">{[["all","Todos"],["processing","En proceso"],["completed","Completados"]].map(([value,label]) => <button key={value} className={filter === value ? "is-active" : ""} onClick={() => setFilter(value)}>{label}</button>)}</div></div>{visible.length ? <div className="uc-job-list">{visible.map((job) => <button key={job.id} onClick={() => void open(job)}><span className={`uc-job-icon is-${job.status}`}>{job.status === "completed" ? <CheckCircle2 size={17} /> : job.status === "failed" ? <AlertCircle size={17} /> : <Clock3 size={17} />}</span><span className="uc-job-main"><strong>{job.objective}</strong><small>{job.kind} · {formatDate(job.created_at)}</small></span><span className={`uc-job-status is-${job.status}`}>{statusCopy[job.status]}</span><FileText size={15} /></button>)}</div> : <div className="uc-task-empty"><strong>No hay trabajos en esta vista.</strong><span>Los análisis largos solicitados por el Agent aparecerán aquí.</span></div>}</section></div>;
}
