import { FormEvent, useEffect, useMemo, useState } from "react";
import { Plus, RefreshCw, UserRound } from "lucide-react";
import { addProfessorCriterion, getProfessors, getSubjectProfessor, type ProfessorData, type ProfessorOverview } from "../api";

const avoidPattern = /penal|avoid|error|negative|rechaz/i;

export default function ProfessorsPage() {
  const [professors, setProfessors] = useState<ProfessorOverview[]>([]);
  const [selectedId, setSelectedId] = useState<number | null>(null);
  const [detail, setDetail] = useState<ProfessorData | null>(null);
  const [criterion, setCriterion] = useState("");
  const [importance, setImportance] = useState(3);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const selected = professors.find((item) => item.id === selectedId) ?? null;

  async function load() { setLoading(true); setError(null); try { const response = await getProfessors(); setProfessors(response.professors); const next = response.professors.find((item) => item.id === selectedId) ?? response.professors[0]; setSelectedId(next?.id ?? null); if (next?.subjects[0]) setDetail(await getSubjectProfessor(next.subjects[0].id)); else setDetail(null); } catch (caught) { setError(caught instanceof Error ? caught.message : "No se pudieron cargar los profesores."); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, []);
  async function selectProfessor(item: ProfessorOverview) { setSelectedId(item.id); setError(null); try { setDetail(item.subjects[0] ? await getSubjectProfessor(item.subjects[0].id) : null); } catch (caught) { setError(caught instanceof Error ? caught.message : "No se pudo cargar el detalle."); } }
  async function submitCriterion(event: FormEvent) { event.preventDefault(); if (!selected?.subjects[0] || !criterion.trim()) return; setSaving(true); setError(null); try { await addProfessorCriterion(selected.id, selected.subjects[0].id, criterion, importance); setCriterion(""); await selectProfessor(selected); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : "No se pudo guardar el criterio."); } finally { setSaving(false); } }
  const criteria = useMemo(() => detail ? [...detail.preferences.filter((item) => item.professor_id === selectedId), ...detail.rubric_criteria.filter((item) => item.professor_id === selectedId).map((item) => ({ id: item.id, preference: `${item.title}${item.description ? `: ${item.description}` : ""}`, importance: item.weight_percentage ?? item.maximum_points ?? 0, source_type: "rubric", source_reference: item.notes, category: "rubric", confidence: 5, professor_id: selectedId! }))].sort((a, b) => b.importance - a.importance) : [], [detail, selectedId]);

  if (loading) return <section className="uc-page-shell uc-state-page"><p className="uc-eyebrow">Profesores</p><h1>Reuniendo criterios reales…</h1></section>;
  if (error && !professors.length) return <section className="uc-page-shell uc-state-page"><p className="uc-eyebrow">Profesores</p><h1>No se pudo cargar Professor Intelligence.</h1><p>{error}</p><button className="uc-primary-action" onClick={() => void load()}>Reintentar <RefreshCw size={15} /></button></section>;
  return <div className="uc-page-shell uc-professors-page"><header className="uc-page-intro"><div><p className="uc-eyebrow">Professor Intelligence</p><h1>Entiende cómo evalúa cada profesor.</h1><p className="uc-page-subtitle">Criterios trazables desde rúbricas, feedback, instrucciones y observaciones reales.</p></div><span className="uc-date-chip"><UserRound size={15} /> {professors.length} registrados</span></header>{error && <div className="uc-inline-error">{error}</div>}{professors.length ? <div className="uc-professor-workspace"><aside>{professors.map((item) => <button key={item.id} className={item.id === selectedId ? "is-active" : ""} onClick={() => void selectProfessor(item)}><strong>{item.name}</strong><span>{item.subjects.map((subject) => subject.name).join(" · ") || "Sin asignatura"}</span><small>{item.criteria_count} criterios · {item.transcript_count} transcripciones</small></button>)}</aside><main>{selected && <><header><p className="uc-eyebrow">Detalle</p><h2>{selected.name}</h2><p>{selected.subjects.map((item) => item.name).join(" · ")}</p></header><section><h3>Cómo evalúa</h3>{criteria.filter((item) => !avoidPattern.test(item.category)).length ? <ol>{criteria.filter((item) => !avoidPattern.test(item.category)).map((item) => <li key={`${item.source_type}-${item.id}`}><strong>{item.preference}</strong><span>Importancia {item.importance} · origen {item.source_type || "observación"}</span>{item.source_reference && <small>{item.source_reference}</small>}</li>)}</ol> : <p className="uc-empty-inline">No hay criterios reales registrados.</p>}</section>{criteria.some((item) => avoidPattern.test(item.category)) && <section className="uc-professor-avoid"><h3>A evitar</h3><ul>{criteria.filter((item) => avoidPattern.test(item.category)).map((item) => <li key={item.id}>{item.preference}</li>)}</ul></section>}<form onSubmit={submitCriterion}><h3>Añadir criterio manual</h3><label><span>Criterio observado</span><textarea rows={3} value={criterion} onChange={(event) => setCriterion(event.target.value)} placeholder="Ej. Valora conclusiones derivadas explícitamente del análisis." /></label><label><span>Importancia</span><select value={importance} onChange={(event) => setImportance(Number(event.target.value))}>{[1, 2, 3, 4, 5].map((value) => <option key={value}>{value}</option>)}</select></label><button className="uc-primary-action" disabled={saving || !criterion.trim()}><Plus size={14} /> Guardar criterio</button></form></>}</main></div> : <section className="uc-professor-empty"><h2>No hay profesores registrados.</h2><p>Puedes crear o asignar uno desde el detalle de una asignatura.</p></section>}</div>;
}
