import { ArrowLeft, ArrowRight, BookOpen, CalendarDays, ChevronRight, Clock3, Plus, RefreshCw, Target, Trophy } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { getAssessments, getDashboard, type Assessment, type DashboardData, type DashboardSubject } from "../api";

function formatDate(value: string | null | undefined) { return value ? new Date(`${value}T00:00:00`).toLocaleDateString("es-ES", { day: "2-digit", month: "short" }) : "Sin fecha"; }
function daysUntil(value: string | null) { if (!value) return "Sin fecha"; const days = Math.ceil((new Date(`${value}T00:00:00`).getTime() - new Date().setHours(0, 0, 0, 0)) / 86400000); return days < 0 ? `Vencida hace ${Math.abs(days)} d` : days === 0 ? "Hoy" : days === 1 ? "Mañana" : `En ${days} días`; }
function subjectState(subject: DashboardSubject) { if (subject.pending_task_count > 0) return { label: `${subject.pending_task_count} tarea${subject.pending_task_count === 1 ? "" : "s"} pendiente${subject.pending_task_count === 1 ? "" : "s"}`, tone: "attention" }; if (subject.grade.required_average_on_remaining != null && subject.grade.required_average_on_remaining > 8) return { label: "Exige atención", tone: "risk" }; return { label: "En curso", tone: "steady" }; }

export default function SubjectsPage({ onSelect }: { onSelect: (subjectId: number) => void }) {
  const [data, setData] = useState<DashboardData | null>(null); const [assessments, setAssessments] = useState<Assessment[]>([]);
  const [readinessBySubject, setReadinessBySubject] = useState<Record<number, number | null>>({}); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [showAssessments, setShowAssessments] = useState(false);
  async function load() { setLoading(true); setError(null); try { const [dashboard, assessmentData] = await Promise.all([getDashboard(), getAssessments()]); setData(dashboard); setAssessments(assessmentData.assessments); const readiness = await Promise.all(dashboard.subjects.map(async (subject) => { try { const detail = await getDashboard(subject.id); return [subject.id, detail.next_boss?.readiness_percentage ?? null] as const; } catch { return [subject.id, null] as const; } })); setReadinessBySubject(Object.fromEntries(readiness)); } catch (caught) { setError(caught instanceof Error ? caught.message : "No se pudieron cargar las asignaturas."); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, []);
  const subjects = useMemo(() => data?.subjects ?? [], [data]); const totalMinutes = subjects.reduce((sum, subject) => sum + subject.study_minutes, 0); const totalXp = subjects.reduce((sum, subject) => sum + subject.xp, 0);
  const pendingAssessments = assessments.filter((item) => item.assessment_date && item.status !== "completed" && item.assessment_date >= new Date().toISOString().slice(0, 10)).sort((a, b) => (a.assessment_date ?? "").localeCompare(b.assessment_date ?? ""));
  const timeRanking = [...subjects].sort((a, b) => b.study_minutes - a.study_minutes); const xpRanking = [...subjects].sort((a, b) => b.xp - a.xp); const maxMinutes = Math.max(1, ...subjects.map((subject) => subject.study_minutes)); const maxXp = Math.max(1, ...subjects.map((subject) => subject.xp));
  if (loading) return <section className="uc-page-shell uc-state-page"><p className="uc-eyebrow">Asignaturas</p><h1>Cargando tu espacio académico…</h1><p>Estamos reuniendo tus notas, actividad y prioridades reales.</p></section>;
  if (error || !data) return <section className="uc-page-shell uc-state-page"><p className="uc-eyebrow">Asignaturas</p><h1>No se pudo cargar el estado académico.</h1><p>{error ?? "La API local no devolvió datos."}</p><button className="uc-primary-action" onClick={() => void load()}>Reintentar <RefreshCw size={16} /></button></section>;
  if (showAssessments) return <div className="uc-page-shell uc-subjects-page"><button className="uc-back-link" onClick={() => setShowAssessments(false)}><ArrowLeft size={16} /> Todas las asignaturas</button><header className="uc-page-intro uc-subject-detail-intro"><div><p className="uc-eyebrow">Agenda académica</p><h1>Evaluaciones pendientes.</h1><p className="uc-page-subtitle">Próximas fechas registradas en tus asignaturas, ordenadas para planificar con antelación.</p></div><div className="uc-date-chip"><CalendarDays size={16} />{pendingAssessments.length} pendiente{pendingAssessments.length === 1 ? "" : "s"}</div></header><section className="uc-assessment-register"><div className="uc-assessment-columns"><span>Evaluación</span><span>Asignatura</span><span>Tipo</span><span>Fecha</span><span>Peso</span></div>{pendingAssessments.length ? pendingAssessments.map((item) => <button key={item.id} onClick={() => onSelect(item.subject_id)}><strong>{item.title}</strong><span>{item.subject_name ?? "Asignatura"}</span><span>{item.assessment_type}</span><span>{formatDate(item.assessment_date)} · {daysUntil(item.assessment_date)}</span><span>{item.weight_percentage != null ? `${item.weight_percentage}%` : "—"}</span></button>) : <div className="uc-empty-inline">No hay evaluaciones pendientes registradas.</div>}</section></div>;
  return <div className="uc-page-shell uc-subjects-page"><header className="uc-page-intro"><div><p className="uc-eyebrow">Espacio académico</p><h1>Asignaturas en perspectiva.</h1><p className="uc-page-subtitle">Una lectura comparativa de notas, preparación y carga de trabajo para decidir dónde poner tu atención.</p></div><div className="uc-subject-page-actions"><button className="uc-new-subject" disabled title="La creación se habilitará cuando la Tool de asignaturas esté disponible para la API HTTP"><Plus size={16} /> Nueva asignatura</button><div className="uc-date-chip"><BookOpen size={16} />{subjects.length} asignatura{subjects.length === 1 ? "" : "s"} activa{subjects.length === 1 ? "" : "s"}</div></div></header><p className="uc-subject-creation-note">La creación de asignaturas estará disponible al conectar de forma segura la capacidad existente del sistema.</p>
    <section className="uc-subjects-summary" aria-label="Resumen de asignaturas"><div><span>Total de tiempo registrado</span><strong>{totalMinutes} min</strong><small>en todas las asignaturas</small></div><div><span>XP académico</span><strong>{totalXp} XP</strong><small>progreso acumulado</small></div><button onClick={() => setShowAssessments(true)}><span>Próximas evaluaciones</span><strong>{pendingAssessments.length}</strong><small>ver evaluaciones pendientes <ArrowRight size={12} /></small></button></section>
    <section className="uc-subject-distributions"><article><div><p className="uc-eyebrow">Distribución</p><h2>Tiempo registrado</h2></div>{timeRanking.map((subject) => <div className="uc-distribution-row" key={subject.id}><span>{subject.name}</span><div className="uc-progress-track"><div className="uc-progress-fill blue" style={{ width: `${(subject.study_minutes / maxMinutes) * 100}%` }} /></div><strong>{subject.study_minutes} min</strong></div>)}</article><article><div><p className="uc-eyebrow">Progresión</p><h2>XP por asignatura</h2></div>{xpRanking.map((subject) => <div className="uc-distribution-row" key={subject.id}><span>{subject.name}</span><div className="uc-progress-track"><div className="uc-progress-fill" style={{ width: `${(subject.xp / maxXp) * 100}%` }} /></div><strong>{subject.xp} XP</strong></div>)}</article></section>
    <section className="uc-subject-ledger"><div className="uc-subject-ledger-head"><div><p className="uc-eyebrow">Registro académico</p><h2>Estado por asignatura</h2></div><span>Selecciona una fila para ver el detalle</span></div><div className="uc-subject-ledger-columns"><span>Asignatura y estado</span><span>Nota / objetivo</span><span>Preparación</span><span>Próxima evaluación</span><span>Actividad</span><span /></div>{subjects.map((subject) => { const state = subjectState(subject); const readiness = readinessBySubject[subject.id]; return <button className="uc-subject-ledger-row" key={subject.id} onClick={() => onSelect(subject.id)}><span className="uc-subject-name"><strong>{subject.name}</strong><small className={`uc-subject-status ${state.tone}`}>{state.label}</small></span><span className="uc-subject-grade"><strong>{subject.grade.current_grade_out_of_10 != null ? subject.grade.current_grade_out_of_10.toFixed(1) : "—"}</strong><small>{subject.grade.target_grade != null ? `objetivo ${subject.grade.target_grade.toFixed(1)}` : "sin objetivo"}</small></span><span className="uc-subject-readiness">{readiness != null ? <><strong>{readiness.toFixed(1)}<small>/ 100</small></strong><span className="uc-progress-track table-track"><span className="uc-progress-fill" style={{ width: `${readiness}%` }} /></span></> : <small>Sin preparación disponible</small>}</span><span className="uc-subject-exam"><CalendarDays size={15} /><span><strong>{subject.next_assessment?.title ?? "Sin evaluación próxima"}</strong><small>{formatDate(subject.next_assessment?.date)}</small></span></span><span className="uc-subject-activity"><span><Clock3 size={14} /> {subject.study_minutes} min</span><span><Target size={14} /> {subject.quiz_average_percentage != null ? `${subject.quiz_average_percentage.toFixed(0)}% quiz` : "sin quiz"}</span><span><Trophy size={14} /> {subject.xp} XP</span></span><ChevronRight size={18} className="uc-subject-chevron" /></button>; })}</section></div>;
}
