import { ArrowLeft, ArrowRight, CalendarDays, Clock3, Flame, RefreshCw, ShieldAlert, Target, Trophy } from "lucide-react";
import { useEffect, useState } from "react";
import { getDashboard, getDecisionPlan, type DashboardData, type DecisionPlan } from "../api";
import { ReadinessChart, StudyMinutesChart } from "../components/Charts";
import Card from "../components/Card";

function formatDate(value: string | null | undefined) { return value ? new Date(`${value}T00:00:00`).toLocaleDateString("es-ES", { day: "numeric", month: "long" }) : "Sin fecha programada"; }
function percent(value: number | null | undefined) { return value == null ? "—" : `${value.toFixed(0)}%`; }

export default function SubjectDetailPage({ subjectId, onBack }: { subjectId: number; onBack: () => void }) {
  const [data, setData] = useState<DashboardData | null>(null); const [plan, setPlan] = useState<DecisionPlan | null>(null);
  const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  async function load() { setLoading(true); setError(null); try { const [dashboard, decision] = await Promise.all([getDashboard(subjectId), getDecisionPlan(60, 3, subjectId)]); setData(dashboard); setPlan(decision); } catch (caught) { setError(caught instanceof Error ? caught.message : "No se pudo cargar la asignatura."); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, [subjectId]);
  if (loading) return <section className="uc-page-shell uc-state-page"><p className="uc-eyebrow">Asignatura</p><h1>Cargando el detalle académico…</h1><p>Calculando nota, preparación y recomendaciones de esta asignatura.</p></section>;
  if (error || !data) return <section className="uc-page-shell uc-state-page"><button className="uc-back-link" onClick={onBack}><ArrowLeft size={16} /> Todas las asignaturas</button><p className="uc-eyebrow">Asignatura</p><h1>No se pudo cargar el detalle.</h1><p>{error ?? "La API local no devolvió datos."}</p><button className="uc-primary-action" onClick={() => void load()}>Reintentar <RefreshCw size={16} /></button></section>;
  const subject = data.subjects[0];
  if (!subject) return <section className="uc-page-shell uc-state-page"><button className="uc-back-link" onClick={onBack}><ArrowLeft size={16} /> Todas las asignaturas</button><p className="uc-eyebrow">Asignatura</p><h1>Esta asignatura ya no está disponible.</h1><p>Vuelve a la lista para consultar el estado académico actualizado.</p></section>;
  const grade = subject.grade; const risk = data.academic_risk; const actions = plan?.actions ?? [];
  return <div className="uc-page-shell uc-subject-detail">
    <button className="uc-back-link" onClick={onBack}><ArrowLeft size={16} /> Todas las asignaturas</button>
    <header className="uc-page-intro uc-subject-detail-intro"><div><p className="uc-eyebrow">Asignatura · estado individual</p><h1>{subject.name}</h1><p className="uc-page-subtitle">Lectura de rendimiento, actividad y prioridades calculada exclusivamente con tu información académica registrada.</p></div><div className="uc-date-chip"><CalendarDays size={16} />{data.next_assessment ? `${formatDate(data.next_assessment.date)} · ${data.next_assessment.title}` : "Sin evaluación próxima"}</div></header>
    <section className="uc-subject-hero-grid">
      <article className="uc-subject-grade-block"><p className="uc-eyebrow">Situación de nota</p><div className="uc-subject-grade-main"><strong>{grade.current_grade_out_of_10 != null ? grade.current_grade_out_of_10.toFixed(1) : "—"}</strong><span>sobre 10</span></div><div className="uc-subject-grade-meta"><span>Objetivo <strong>{grade.target_grade != null ? grade.target_grade.toFixed(1) : "—"}</strong></span><span>Evaluado <strong>{grade.evaluated_weight_percentage.toFixed(0)}%</strong></span></div><div className="uc-progress-track"><div className="uc-progress-fill blue" style={{ width: `${Math.min(100, grade.evaluated_weight_percentage)}%` }} /></div><p>{grade.required_average_on_remaining != null ? `Necesitas una media de ${grade.required_average_on_remaining.toFixed(1)} en lo restante para alcanzar tu objetivo.` : "No hay suficiente información para calcular la media necesaria."}</p></article>
      <aside className="uc-subject-progression"><div><Trophy size={17} /><span>Progreso UniCore</span></div><strong>{subject.xp} XP</strong><p>Nivel {data.hero.level} · {data.hero.xp_until_next_level} XP para el siguiente nivel</p><div className="uc-progress-track compact"><div className="uc-progress-fill" style={{ width: `${data.hero.level_progress_percentage}%` }} /></div><div className="uc-subject-streak"><Flame size={15} /> Racha actual <strong>{data.hero.current_streak} día(s)</strong></div></aside>
    </section>
    <section className="uc-kpis uc-subject-kpis"><div className="uc-kpi"><span>Estudio</span><strong>{data.metrics.study_minutes_last_7_days} min</strong><small>últimos 7 días</small></div><div className="uc-kpi"><span>Quiz medio</span><strong>{percent(data.metrics.quiz_average_percentage)}</strong><small>{data.metrics.quiz_attempt_count} intento(s)</small></div><div className="uc-kpi"><span>Tareas activas</span><strong>{data.metrics.pending_task_count}</strong><small>{data.metrics.overdue_task_count} vencida(s)</small></div><div className="uc-kpi"><span>Repasos</span><strong>{data.metrics.due_review_count}</strong><small>pendientes hoy</small></div></section>
    <section className="uc-dashboard-grid uc-dashboard-grid-charts"><StudyMinutesChart activity={data.daily_activity} totalMinutes={data.metrics.study_minutes_last_7_days} /><ReadinessChart boss={data.next_boss} /></section>
    <section className="uc-subject-detail-grid">
      <Card eyebrow="Decision Engine" title="Próximas acciones" className="uc-subject-actions"><div className="uc-action-list">{actions.length ? actions.map((action, index) => <div className="uc-action-row" key={`${action.type}-${action.source_id}`}><div className="uc-action-index">{String(index + 1).padStart(2, "0")}</div><div className="uc-action-main"><strong>{action.title}</strong><span>{action.allocated_minutes} min · prioridad {action.priority} · {action.reasons.join(" ")}</span></div><ArrowRight size={16} /></div>) : <div className="uc-empty-inline">No hay recomendaciones prioritarias para los próximos 60 minutos.</div>}</div></Card>
      <Card eyebrow="Riesgo académico" title="Señal actual" className="uc-risk-panel">{risk ? <><div className="uc-risk-score"><ShieldAlert size={18} /><strong>{risk.risk_level ?? "Sin clasificar"}</strong>{risk.risk_score != null && <span>{risk.risk_score.toFixed(0)}/100</span>}</div><p>{risk.summary ?? "El riesgo se calcula con las evidencias académicas disponibles."}</p>{risk.reasons?.length ? <ul>{risk.reasons.slice(0, 3).map((reason) => <li key={reason}>{reason}</li>)}</ul> : null}</> : <div className="uc-empty-inline">Aún no hay una señal de riesgo disponible para esta asignatura.</div>}</Card>
    </section>
    <section className="uc-subject-analytics"><div className="uc-section-heading"><div><p className="uc-eyebrow">Analítica reciente</p><h2>Indicadores de las últimas dos semanas</h2></div><span>Comparación disponible en backend</span></div>{data.analytics ? <div className="uc-analytics-strip"><div><span>Días activos</span><strong>{data.analytics.current.active_days}</strong><small>{data.analytics.trends.active_days_change_percentage != null ? `${data.analytics.trends.active_days_change_percentage > 0 ? "+" : ""}${data.analytics.trends.active_days_change_percentage.toFixed(0)}% vs. periodo anterior` : "sin comparación"}</small></div><div><span>Foco medio</span><strong>{data.analytics.current.average_focus != null ? `${data.analytics.current.average_focus.toFixed(1)}/5` : "—"}</strong><small>sesiones con valoración</small></div><div><span>Cumplimiento del plan</span><strong>{percent(data.analytics.current.plan_completion_percentage)}</strong><small>sesiones planificadas</small></div><div><span>Índice de estudio</span><strong>{percent(data.analytics.current.study_efficiency_index)}</strong><small>foco, quizzes y planificación</small></div></div> : <div className="uc-empty-inline">No hay analítica suficiente para este periodo.</div>}</section>
    <section className="uc-subject-future"><p className="uc-eyebrow">Próximamente</p><div><strong>Evaluaciones, materiales, sesiones detalladas y Knowledge Map</strong><span>Estas áreas ya existen en el backend, pero aún no se exponen por la API HTTP actual. No se muestran datos ficticios.</span></div></section>
  </div>;
}
