import { CalendarDays, Check, CheckCircle2, Clock3, Plus, RefreshCw, SlidersHorizontal, Target, X } from "lucide-react";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { createTask, getDashboard, getDecisionPlan, getTasks, updateTask, type DashboardData, type DecisionPlan, type TasksData } from "../api";

const durations = [15, 30, 45, 60, 90];
const taskTypes = [["assignment", "Entrega"], ["exam", "Examen"], ["reading", "Lectura"], ["project", "Proyecto"], ["presentation", "Presentación"], ["class_preparation", "Preparación de clase"], ["administrative", "Administrativa"], ["other", "Otra"]] as const;
type Scope = "active" | "overdue" | "today" | "upcoming" | "undated";
function dueLabel(days: number | null) { if (days == null) return "Sin fecha"; if (days < 0) return `Vencida hace ${Math.abs(days)} día${Math.abs(days) === 1 ? "" : "s"}`; if (days === 0) return "Hoy"; if (days === 1) return "Mañana"; return `En ${days} días`; }
function priorityLabel(value: number) { if (value >= 5) return "Crítica"; if (value >= 4) return "Alta"; if (value >= 3) return "Media"; return "Baja"; }

export default function TasksPage() {
  const [data, setData] = useState<TasksData | null>(null); const [dashboard, setDashboard] = useState<DashboardData | null>(null); const [plan, setPlan] = useState<DecisionPlan | null>(null); const [duration, setDuration] = useState(60); const [scope, setScope] = useState<Scope>("active"); const [loading, setLoading] = useState(true); const [planning, setPlanning] = useState(false); const [error, setError] = useState<string | null>(null); const [showCreate, setShowCreate] = useState(false); const [saving, setSaving] = useState(false); const [notice, setNotice] = useState<string | null>(null); const [formError, setFormError] = useState<string | null>(null); const [form, setForm] = useState({ title: "", subject_id: "", task_type: "assignment", priority: "3", due_date: "", estimated_minutes: "", description: "", notes: "" });
  async function loadTasks() { setLoading(true); setError(null); try { const [tasks, nextPlan, subjects] = await Promise.all([getTasks(), getDecisionPlan(duration, 5), getDashboard()]); setData(tasks); setPlan(nextPlan); setDashboard(subjects); } catch (caught) { setError(caught instanceof Error ? caught.message : "No se pudieron cargar las tareas."); } finally { setLoading(false); } }
  async function changeDuration(minutes: number) { setDuration(minutes); setPlanning(true); try { setPlan(await getDecisionPlan(minutes, 5)); } catch (caught) { setError(caught instanceof Error ? caught.message : "No se pudo calcular el plan."); } finally { setPlanning(false); } }
  async function submit(event: FormEvent) { event.preventDefault(); if (!form.title.trim()) { setFormError("Escribe un título para la tarea."); return; } setSaving(true); setFormError(null); try { await createTask({ title: form.title, subject_id: form.subject_id ? Number(form.subject_id) : null, task_type: form.task_type, priority: Number(form.priority), due_date: form.due_date || null, estimated_minutes: form.estimated_minutes ? Number(form.estimated_minutes) : null, description: form.description || null, notes: form.notes || null }); setShowCreate(false); setForm({ title: "", subject_id: "", task_type: "assignment", priority: "3", due_date: "", estimated_minutes: "", description: "", notes: "" }); setNotice("La tarea se ha añadido correctamente."); await loadTasks(); window.setTimeout(() => setNotice(null), 3000); } catch (caught) { setFormError(caught instanceof Error ? caught.message : "No se pudo crear la tarea."); } finally { setSaving(false); } }
  async function complete(taskId: number) { try { await updateTask(taskId, { status: "completed" }); setNotice("Tarea completada."); await loadTasks(); window.setTimeout(() => setNotice(null), 2500); } catch (caught) { setError(caught instanceof Error ? caught.message : "No se pudo completar la tarea."); } }
  useEffect(() => { void loadTasks(); }, []);
  const tasks = useMemo(() => (data?.tasks ?? []).filter(({ task }) => scope === "overdue" ? task.is_overdue : scope === "today" ? task.days_until_due === 0 : scope === "upcoming" ? task.days_until_due != null && task.days_until_due > 0 : scope === "undated" ? task.due_date == null : true), [data, scope]);
  const counts = { overdue: data?.tasks.filter(({ task }) => task.is_overdue).length ?? 0, today: data?.tasks.filter(({ task }) => task.days_until_due === 0).length ?? 0, inProgress: data?.tasks.filter(({ task }) => task.status === "in_progress").length ?? 0 };
  if (loading && !data) return <section className="uc-page-shell uc-state-page"><p className="uc-eyebrow">Tareas</p><h1>Ordenando tu carga académica…</h1><p>UniCore está leyendo fechas, progreso y prioridad.</p></section>;
  if (error && !data) return <section className="uc-page-shell uc-state-page"><p className="uc-eyebrow">Tareas</p><h1>No se pudo cargar el trabajo pendiente.</h1><p>{error}</p><button className="uc-primary-action" onClick={() => void loadTasks()}>Reintentar <RefreshCw size={16} /></button></section>;
  return <div className="uc-page-shell uc-tasks-page"><header className="uc-page-intro"><div><p className="uc-eyebrow">Ejecución académica</p><h1>Tareas con contexto.</h1><p className="uc-page-subtitle">Fechas, avance y prioridad real para separar lo urgente de lo que simplemente hace ruido.</p></div><div className="uc-page-actions"><button className="uc-new-subject" onClick={() => { setShowCreate(true); setFormError(null); }}><Plus size={16} /> Añadir tarea</button><div className="uc-date-chip"><CheckCircle2 size={16} />{data?.count ?? 0} activa{data?.count === 1 ? "" : "s"}</div></div></header>{notice && <div className="uc-inline-success">{notice}</div>}{error && <div className="uc-inline-error">{error}</div>}
    <section className="uc-task-summary"><div><span>Vencidas</span><strong className={counts.overdue ? "is-danger" : ""}>{counts.overdue}</strong><small>requieren atención</small></div><div><span>Para hoy</span><strong>{counts.today}</strong><small>con fecha actual</small></div><div><span>En progreso</span><strong>{counts.inProgress}</strong><small>trabajo iniciado</small></div></section>
    <section className="uc-planner-block"><div className="uc-planner-copy"><p className="uc-eyebrow">Plan de trabajo</p><h2>Planifica tu tiempo</h2><p>Elige cuánto tiempo tienes. UniCore recalcula qué acciones caben y por qué merecen atención.</p></div><div className="uc-duration-control" aria-label="Duración disponible">{durations.map((minutes) => <button key={minutes} className={duration === minutes ? "is-active" : ""} onClick={() => void changeDuration(minutes)}>{minutes}<span>min</span></button>)}</div><div className="uc-planner-result">{planning ? <div className="uc-empty-inline">Calculando el plan…</div> : plan?.actions.length ? plan.actions.map((action, index) => <article key={`${action.type}-${action.source_id}`}><span className="uc-action-index">{String(index + 1).padStart(2, "0")}</span><div><strong>{action.title}</strong><p>{action.reasons.join(" ")}</p><small>{action.subject_name ?? "UniCore"} · {action.allocated_minutes} min · prioridad {action.priority}</small></div><div className="uc-plan-score"><Target size={15} />{action.score.toFixed(0)}</div></article>) : <div className="uc-empty-inline">No hay acciones prioritarias para este bloque.</div>}</div></section>
    <section className="uc-task-register"><div className="uc-task-register-head"><div><p className="uc-eyebrow">Registro activo</p><h2>Trabajo pendiente</h2></div><div className="uc-task-filters"><SlidersHorizontal size={14} />{([['active','Todas'],['overdue','Vencidas'],['today','Hoy'],['upcoming','Próximas'],['undated','Sin fecha']] as const).map(([value, label]) => <button key={value} className={scope === value ? "is-active" : ""} onClick={() => setScope(value)}>{label}</button>)}</div></div>{tasks.length === 0 ? <div className="uc-task-empty"><strong>No hay tareas en esta vista.</strong><span>{data?.count ? "Prueba otro filtro para revisar tu trabajo activo." : "Añade una tarea para empezar a planificar."}</span></div> : <div className="uc-task-list">{tasks.map(({ task, planning: taskPlanning }) => <article className={`uc-task-row ${task.is_overdue ? "is-overdue" : ""}`} key={task.id}><div className="uc-task-priority"><span>{priorityLabel(task.priority)}</span><strong>{taskPlanning.planning_score.toFixed(0)}</strong></div><div className="uc-task-main"><div><strong>{task.title}</strong><span>{task.subject_name ?? "Sin asignatura"} · {task.task_type}</span></div>{task.description && <p>{task.description}</p>}<div className="uc-task-progress"><div className="uc-progress-track"><div className="uc-progress-fill" style={{ width: `${task.progress_percentage}%` }} /></div><span>{task.progress_percentage}%</span></div></div><div className="uc-task-meta"><span className={task.is_overdue ? "is-danger" : ""}><CalendarDays size={14} />{dueLabel(task.days_until_due)}</span><span><Clock3 size={14} />{task.remaining_minutes != null ? `${task.remaining_minutes} min restantes` : "Sin estimación"}</span><button className="uc-complete-task" onClick={() => void complete(task.id)}><Check size={13} /> Marcar completada</button></div></article>)}</div>}</section>
    {showCreate && <div className="uc-form-backdrop" onMouseDown={() => !saving && setShowCreate(false)}><form className="uc-form-modal uc-task-form" onSubmit={submit} onMouseDown={(event) => event.stopPropagation()}><header><div><p className="uc-eyebrow">Trabajo académico</p><h2>Añadir tarea</h2></div><button type="button" onClick={() => setShowCreate(false)} aria-label="Cerrar formulario"><X size={18} /></button></header><div className="uc-form-grid"><label className="is-wide">Título<span>Obligatorio</span><input autoFocus value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} /></label><label>Asignatura<span>Opcional</span><select value={form.subject_id} onChange={(event) => setForm({ ...form, subject_id: event.target.value })}><option value="">Sin asignatura</option>{dashboard?.subjects.map((subject) => <option key={subject.id} value={subject.id}>{subject.name}</option>)}</select></label><label>Tipo<select value={form.task_type} onChange={(event) => setForm({ ...form, task_type: event.target.value })}>{taskTypes.map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label><label>Prioridad<select value={form.priority} onChange={(event) => setForm({ ...form, priority: event.target.value })}>{[1,2,3,4,5].map((value) => <option key={value} value={value}>{value} · {priorityLabel(value)}</option>)}</select></label><label>Fecha límite<span>Opcional</span><input type="date" value={form.due_date} onChange={(event) => setForm({ ...form, due_date: event.target.value })} /></label><label>Estimación<span>Minutos</span><input type="number" min="1" value={form.estimated_minutes} onChange={(event) => setForm({ ...form, estimated_minutes: event.target.value })} /></label><label className="is-wide">Descripción<span>Opcional</span><textarea rows={3} value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} /></label><label className="is-wide">Notas<span>Opcional</span><textarea rows={2} value={form.notes} onChange={(event) => setForm({ ...form, notes: event.target.value })} /></label></div>{formError && <p className="uc-form-error">{formError}</p>}<footer><button type="button" onClick={() => setShowCreate(false)} disabled={saving}>Cancelar</button><button className="uc-primary-action" disabled={saving}>{saving ? "Guardando…" : "Añadir tarea"}</button></footer></form></div>}
  </div>;
}
