import { ChangeEvent, useEffect, useState } from "react";
import { FileText, Upload } from "lucide-react";
import { getDashboard, getSubjectDocuments, uploadSubjectMaterial, type DashboardData, type SubjectDocumentsData } from "../api";

export default function TranscriptsPage() {
  const [dashboard, setDashboard] = useState<DashboardData | null>(null);
  const [subjectId, setSubjectId] = useState<number | null>(null);
  const [documents, setDocuments] = useState<SubjectDocumentsData["documents"]>([]);
  const [uploading, setUploading] = useState(false);
  const [notice, setNotice] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  async function loadSubject(id: number) { setSubjectId(id); const response = await getSubjectDocuments(id); setDocuments(response.documents.filter((item) => item.document_type === "transcript")); }
  useEffect(() => { getDashboard().then(async (data) => { setDashboard(data); if (data.subjects[0]) await loadSubject(data.subjects[0].id); }).catch((caught) => setError(caught instanceof Error ? caught.message : "No se pudo cargar.")); }, []);
  async function upload(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file || subjectId == null) return; setUploading(true); setError(null); try { const result = await uploadSubjectMaterial(subjectId, file, { document_type: "transcript", material_type: "class_notes" }); setNotice(result.duplicate ? "La transcripción ya estaba registrada." : "Transcripción preparada e indexada."); await loadSubject(subjectId); } catch (caught) { setError(caught instanceof Error ? caught.message : "No se pudo subir la transcripción."); } finally { setUploading(false); event.target.value = ""; } }
  return <div className="uc-page-shell uc-transcripts-page"><header className="uc-page-intro"><div><p className="uc-eyebrow">Academic Memory · futuro</p><h1>Transcripciones de clase.</h1><p className="uc-page-subtitle">Las transcripciones permitirán a UniCore aprender qué enfatiza el profesor y conectar el contenido de clase con tus materiales.</p></div>{dashboard?.subjects.length ? <label className="uc-subject-select"><span>Asignatura</span><select value={subjectId ?? ""} onChange={(event) => void loadSubject(Number(event.target.value))}>{dashboard.subjects.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label> : null}</header><section className="uc-transcript-future"><div><p className="uc-eyebrow">Pipeline futuro</p><h2>Audio y análisis estructurado</h2><p>La captura de audio y la extracción automática de énfasis, advertencias, ejemplos y pistas de examen llegarán en una integración posterior.</p><button disabled>Transcribir audio · próximamente</button></div><div><p className="uc-eyebrow">Disponible ahora</p><h2>Importar texto manualmente</h2><p>Los archivos TXT y MD usan el pipeline documental real, con chunks y embeddings persistentes.</p><label className="uc-primary-action"><Upload size={15} /> {uploading ? "Procesando…" : "Subir .txt o .md"}<input type="file" accept=".txt,.md,text/plain,text/markdown" onChange={(event) => void upload(event)} disabled={uploading || subjectId == null} /></label></div></section>{notice && <div className="uc-inline-success">{notice}</div>}{error && <div className="uc-inline-error">{error}</div>}<section className="uc-transcript-list"><header><p className="uc-eyebrow">Memoria de clase</p><h2>Transcripciones importadas</h2></header>{documents.length ? documents.map((item) => <article key={item.id}><FileText size={17} /><div><strong>{item.title}</strong><span>{item.chunk_count} fragmentos · {item.character_count.toLocaleString("es-ES")} caracteres</span></div><small>{item.created_at ? new Date(item.created_at).toLocaleDateString("es-ES") : ""}</small></article>) : <div className="uc-task-empty"><strong>No hay transcripciones.</strong><span>Importa una transcripción manual cuando dispongas del texto.</span></div>}</section></div>;
}
